services:
  postgres_server:
    image: 'postgres:12'
    container_name: 'postgres_server'
    ports:
      - '5433:5432'
    env_file:
      - "postgres.env"
    networks:
      - net-db
  bibliotopia_backend:
    container_name: 'bibliotopia_backend'
    ports:
      - '8081:8080'
    build:
      context: .
      dockerfile: 'Dockerfile'
    env_file:
      - 'app.env'
    depends_on:
      - postgres_server
    networks:
      - net-db

volumes:
  postgres-data:

networks:
  net-db:
    driver: bridge
