spring:
  application:
    name: bibliotopia
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  liquibase:
    change-log: db/changelog/db.changelog-master.xml
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
  mail:
    host: ${SMTP_HOST}
    port: ${SMTP_PORT}
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

variables:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION} #In ms
      refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION} #In ms
    email-verification-expiration: ${EMAIL_VERIFICATION_EXPIRATION} #In hours
  url:
    email-verification: ${EMAIL_VERIFICATION_URL}